---
- name: Install dependencies
  ansible.builtin.package:
    name: "{{ go_dependencies }}"
    state: present

- name: Install go
  environment:
    GOPATH: "{{ gopath }}"
  ansible.builtin.apt:
    name: golang-go
    state: present

- name: Install go packages
  include_tasks: "install_packages.yml"
  loop: "{{ go_packages | dict2items }}"
  loop_control:
    loop_var: package
