---
- name: Verify alacritty role
  hosts: all
  tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - 'yml'

    - name: Stat {{ alacritty_dir }}
      ansible.builtin.stat:
        path: "{{ alacritty_dir }}"
      register: rc

    - name: Check if {{ alacritty_dir }} link exists
      ansible.builtin.assert:
        that:
          - rc.stat.islnk is defined
          - rc.stat.islnk
        success_msg: "{{ alacritty_dir }} link exists"
        fail_msg: "{{ alacritty_dir }} link does not exist"

    - name: Stat {{ cargo_dir }}/bin/alacritty
      ansible.builtin.stat:
        path: "{{ cargo_dir }}/bin/alacritty"
      register: rc

    - name: Check if {{ cargo_dir }}/bin/alacritty exists
      ansible.builtin.assert:
        that:
          - rc.stat.exists
        success_msg: "Alacritty is installed!"
        fail_msg: "Alacritty is not installed!"
