---
user_home: "/home/mcst"
dotfiles_url: https://github.com/mcanueste/dotfiles.git
dotfiles_dir: "{{ user_home }}/.dotfiles"
cargo_dir: "{{ user_home }}/.cargo"
config_dir: "{{ user_home }}/.config"
starship_path: "{{ user_home }}/.cargo/bin/starship"
starship_dir: "{{ user_home }}/.config/starship"

starship_dependencies:
  - ca-certificates
  - build-essential
  - pkg-config
  - curl
  - cmake 
