---
cargo_dir: "{{ ansible_env.HOME }}/.cargo"

rust_dependencies:
  - ca-certificates
  - build-essential
  - fontconfig
  - curl
  - cmake 
  - pkg-config
  - libfreetype6-dev
  - libfontconfig1-dev
  - libxcb-xfixes0-dev
  - libxkbcommon-dev
  - python3
  - openssl
  - libssl-dev
  - libcurl4-openssl-dev
  - libxml2-dev

rust_packages:
  - alacritty
  - starship
  - bottom
  - hyperfine
  - hurl
  - just
