---
packages:
  # Install dependencies
  - ca-certificates
  - software-properties-common
  - fuse
  - libfuse2
  - git

  # CLI tools
  - rsync
  - htop
  - ncdu
  - ripgrep
  - fd-find

  # CLI tools that require config or bash modification
  - tmux
  - zoxide
  - fzf
  - exa
  - bat

  # Networking
  - wireguard

  # To be built
  # - dive

ppa_packages:
  # Editor
  neovim: "ppa:neovim-ppa/unstable"


app_image_packages:
  # Notes
  obsidian: "obsidianmd/obsidian-releases/releases/download/v1.1.9/Obsidian-1.1.9.AppImage"


apt_repo_packages:
  brave-browser: 
    gpg:
      url: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
      dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    repository: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    # dest: /etc/apt/sources.list.d/brave-browser-release.list

git_repositories:
  asdf: 
    url: https://github.com/asdf-vm/asdf.git 
    dest: ~/.local/asdf 
    branch: v0.11.1
