---
- name: Verify aptrepo role
  hosts: all
  tasks:
    - name: Install verification dependencies
      apt:
        name: python3-apt
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - 'yml'

    - name: Check if aptrepo packages are installed
      ansible.builtin.assert:
        that:
          - "'{{ item.key }}' in ansible_facts.packages"
        fail_msg: "{{ item.key }} is not installed!"
        success_msg: "{{ item.key }} is installed!"
      loop: "{{ aptrepo_packages | dict2items }}"
