---
- name: Check if dotfiles repository exists
  ansible.builtin.git:
    repo: "{{ dotfiles_url }}"
    dest: "{{ dotfiles_dir }}"
    single_branch: yes
    version: main
    clone: no
    update: no

- name: Check if {{ ansible_env.HOME }}/.bashrc exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bashrc"
  register: rc

- name: Rename existing {{ ansible_env.HOME }}/.bashrc file 
  ansible.builtin.command: mv {{ ansible_env.HOME }}/.bashrc {{ ansible_env.HOME }}/.bashrc.bak
  when: 
    - rc.stat.exists
    - rc.stat.islnk is defined and not rc.stat.islnk

- name: Create {{ ansible_env.HOME }}/.bashrc symbolic link
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/configs/bash/bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: link
    mode: 0755
  when: 
    - rc.stat.islnk is defined and not rc.stat.islnk
