---
- name: Check if dotfiles repository exists
  ansible.builtin.git:
    repo: "{{ dotfiles_url }}"
    dest: "{{ dotfiles_dir }}"
    version: main
    clone: no
    update: no

- name: Check if {{ user_home }}/.bashrc exists
  ansible.builtin.stat:
    path: "{{ user_home }}/.bashrc"
  register: rc

- name: Rename existing {{ user_home }}/.bashrc file 
  ansible.builtin.command: mv {{ user_home }}/.bashrc {{ user_home }}/.bashrc.bak
  when: 
    - rc.stat.exists
    - rc.stat.islnk is defined and not rc.stat.islnk

- name: Create {{ user_home }}/.bashrc symbolic link
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/configs/bash/bashrc"
    dest: "{{ user_home }}/.bashrc"
    state: link
    mode: 0755
  when: 
    - rc.stat.islnk is defined and not rc.stat.islnk
