---
apt_packages:
  - ca-certificates
  - software-properties-common
  - git
  - rsync
  - xclip
  - xsel
  - wl-clipboard
  - htop
  - ncdu
  - ripgrep
  - fd-find
  - bat
  - exa
  - fzf
  - zoxide
  - shellcheck
  - bash-completion
  - hyperfine
  - solaar
  - telegram-desktop
