---
user_home: "/home/mcst"
dotfiles_url: https://github.com/mcanueste/dotfiles.git
dotfiles_dir: "{{ user_home }}/.dotfiles"
cargo_dir: "{{ user_home }}/.cargo"
config_dir: "{{ user_home }}/.config"
nvim_dir: "{{ user_home }}/.config/nvim"
nvim_ppa: "ppa:neovim-ppa/unstable"

nvim_dependencies:
  - software-properties-common
