---
- name: Verify
  hosts: all

  tasks:
    - name: Install verification dependencies
      apt:
        name: python3-apt
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - 'yml'

    - name: Check if packages are installed
      ansible.builtin.assert:
        that:
          - "'{{ item }}' in ansible_facts.packages"
        fail_msg: "{{ item }} is not installed!"
        success_msg: "{{ item }} is installed!"
      loop: "{{ packages }}"

    - name: Check if PPA packages are installed
      ansible.builtin.assert:
        that:
          - "'{{ item.key }}' in ansible_facts.packages"
        fail_msg: "{{ item.key }} is not installed!"
        success_msg: "{{ item.key }} is installed!"
      loop: "{{ ppa_packages | dict2items }}"

    - name: Register installed AppImage packages
      shell: "ls -1 ~/.local/appimage"
      register: installed_app_image_packages

    - name: Check if AppImage packages are installed
      ansible.builtin.assert:
        that:
          - "'{{ item.key }}' in {{ installed_app_image_packages.stdout_lines }}"
        fail_msg: "{{ item.key }} is not installed!"
        success_msg: "{{ item.key }} is installed!"
      loop: "{{ app_image_packages | dict2items }}"

    - name: Check if APT Repo packages are installed
      ansible.builtin.assert:
        that:
          - "'{{ item.key }}' in ansible_facts.packages"
        fail_msg: "{{ item.key }} is not installed!"
        success_msg: "{{ item.key }} is installed!"
      loop: "{{ apt_repo_packages | dict2items }}"

    - name: Check if git repositories are cloned
      ansible.builtin.git:
        repo: "{{ item.value.url }}"
        dest: "{{ item.value.dest }}"
        version: "{{ item.value.branch }}"
        single_branch: yes
        clone: no
        update: no
      loop: "{{ git_repositories | dict2items }}"
