---
- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: "{{ go_dependencies }}"
    state: present

- name: Install go
  become: true
  environment:
    GOPATH: "{{ gopath }}"
  ansible.builtin.apt:
    name: golang-go
    state: present
