---
- name: Verify starship role
  hosts: all
  tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - 'yml'

    - name: Stat {{ starship_dir }}
      ansible.builtin.stat:
        path: "{{ starship_dir }}"
      register: rc

    - name: Check if {{ starship_dir }} link exists
      ansible.builtin.assert:
        that:
          - rc.stat.islnk is defined
          - rc.stat.islnk
        success_msg: "{{ starship_dir }} link exists"
        fail_msg: "{{ starship_dir }} link does not exist"

    - name: Stat {{ cargo_dir }}/bin/starship
      ansible.builtin.stat:
        path: "{{ cargo_dir }}/bin/starship"
      register: rc

    - name: Check if {{ cargo_dir }}/bin/starship exists
      ansible.builtin.assert:
        that:
          - rc.stat.exists
        success_msg: "starship is installed!"
        fail_msg: "starship is not installed!"
