---
- name: Verify dotfiles role
  hosts: all
  tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - 'yml'

    - name: Check if dotfiles repository exists
      ansible.builtin.git:
        repo: "{{ dotfiles_url }}"
        dest: "{{ dotfiles_dir }}"
        single_branch: yes
        version: main
        clone: no
        update: no
