---
- name: Verify bash role
  hosts: all
  tasks:
    - name: Stat ~/.bashrc
      ansible.builtin.stat:
        path: ~/.bashrc
      register: rc

    - name: Check if ~/.bashrc link exists
      ansible.builtin.assert:
        that:
          - rc.stat.islnk is defined
          - rc.stat.islnk
        success_msg: "~/.bashrc link exists"
        fail_msg: "~/.bashrc link does not exist"
