---
- name: Install packages with apt
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Install PPA Packages 
  block:
    - name: Add PPA's
      ansible.builtin.apt_repository:
        repo: "{{ item.value }}"
      loop: "{{ ppa_packages | dict2items }}"

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item.key }}"
        state: present
      loop: "{{ ppa_packages | dict2items }}"

- name: Install AppImage Packages
  block:
    - name: Create ~/.local/appimage directory
      ansible.builtin.file:
        path: ~/.local/appimage
        state: directory
        mode: 0755
        recurse: true
    
    - name: Download AppImage packages
      ansible.builtin.get_url:
        url: "https://github.com/{{ item.value }}"
        dest: "~/.local/appimage/{{ item.key }}"
        mode: 0755
      loop: "{{ app_image_packages | dict2items }}"

- name: Install APT Repo Packages
  block:
    - name: Add GPG keys
      ansible.builtin.get_url:
        url: "{{ item.value.gpg.url }}"
        dest: "{{ item.value.gpg.dest }}"
        mode: 0755
      loop: "{{ apt_repo_packages | dict2items }}"

    - name: Add repositories to index
      ansible.builtin.apt_repository:
        repo: "{{ item.value.repository }}"
        state: present
      loop: "{{ apt_repo_packages | dict2items }}"

    - name: Install APT Repo Packages
      ansible.builtin.apt:
        name: "{{ item.key }}"
        state: present
      loop: "{{ apt_repo_packages | dict2items }}"

- name: Clone git repositories
  ansible.builtin.git:
    repo: "{{ item.value.url }}"
    dest: "{{ item.value.dest }}"
    version: "{{ item.value.branch }}"
    single_branch: yes
  loop: "{{ git_repositories | dict2items }}"
