---
user_home: "/home/mcst"
cargo_dir: "{{ user_home }}/.cargo"

rust_dependencies:
  - ca-certificates
  - build-essential
  - curl
  - cmake 
  - pkg-config
  - openssl
  - libssl-dev
  - libcurl4-openssl-dev
  - libxml2-dev

rust_packages:
  - bottom
  - hurl
  - just
