---
- hosts: localhost
  connection: local
  tasks:
    - name: Include dotfiles role
      include_role:
        name: "dotfiles"

    - name: Include asdf role
      include_role:
        name: "asdf"

    - name: Include go role
      include_role:
        name: "go"

    - name: Include rust role
      include_role:
        name: "rust"

    - name: Include apt role
      include_role:
        name: "apt"

    - name: Include aptrepo role
      include_role:
        name: "aptrepo"

    - name: Include ppa role
      include_role:
        name: "ppa"

    - name: Include appimage role
      include_role:
        name: "appimage"

    - name: Include gopkg role
      include_role:
        name: "gopkg"

    - name: Include rustpkg role
      include_role:
        name: "rustpkg"

    - name: Include bash
      include_role:
        name: "bash"

    - name: Include starship role
      include_role:
        name: "starship"

    - name: Include alacritty role
      include_role:
        name: "alacritty"

    - name: Include nvim role
      include_role:
        name: "nvim"
