---
- name: Verify rust package installations
  hosts: all
  tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - 'yml'

    - name: Stat cargo dir
      stat:
        path: "{{ cargo_dir }}"
      register: cargo

    - name: Check if cargo is installed
      ansible.builtin.assert:
        that:
          - cargo.stat.exists
          - cargo.stat.isdir
        success_msg: "rustup is installed!"
        fail_msg: "rustup is not installed!"

    - name: Register installed rust packages
      shell: "ls -1 {{ cargo_dir }}/bin"
      register: installed_rust_packages
    
    - name: Check if rust packages are installed
      loop: "{{ rust_packages }}"
      ansible.builtin.assert:
        that: >
          ("'{{ item }}' in {{ installed_rust_packages.stdout_lines }}") or
          ("'{{ item | replace('o','') }}' in {{ installed_rust_packages.stdout_lines }}")
        fail_msg: "{{ item }} is not installed!"
        success_msg: "{{ item }} is installed!"
