;==========================================================
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;==========================================================

[colors]
background = #1E1D2F
background-alt = #312F43

foreground = #D9E0EE
primary = #ABE9B3
secondary = #8ABEB7
alert = #F28FAD
disabled = #707880

[bar/myconf]
width = 100%
height = 2.7%
radius = 6

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
border-size = 4
border-color = #00000000
padding-left = 3
padding-right = 3
module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = BlexMono Nerd Font Mono:style=Text,Regular;4
; font-0 = SourceCodePro Nerd Font:style=Text,Regular;4

modules-left = xworkspaces xwindow
modules-right = pulseaudio wlan eth date battery

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = right
wm-restack = 
override-redirect = false 

[module/backlight]
type = internal/backlight
card = intel_backlight
format = <label>
; format = <label>
enable-scroll = true
label = %percentage%%
ramp-0 = 🌕
ramp-1 = 🌔
ramp-2 = 🌓
ramp-3 = 🌒
ramp-4 = 🌑

[module/battery]
type = internal/battery
full-at = 98
battery = BAT0
adapter = AC
poll-interval = 5
time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
bar-capacity-width = 10
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
animation-discharging-framerate = 500
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/date]
type = internal/date
interval = 1.0
date = %Y-%m-%d%
time = %H:%M
date-alt = %A, %d %B %Y
time-alt = %H:%M:%S
label = %date% %time%

[settings]
screenchange-reload = true
pseudo-transparency = true

