theme = "catppuccin_mocha"

[editor]
mouse = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]


